command:  ["python", "-m", "app.run"]
env:
  - name: 'DATABASE_URL'
    value: 'postgresql://ars.1001%40gmail.com@ep-weathered-dew-d8vbfjbw.database.us-east-2.cloud.databricks.com/databricks_postgres?sslmode=require'
